minio:
  accessKey: minio
  endpoint: http://myserver.com:9000
  secretKey: minio@123
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  datasource:
    password: GUjPhs5mwFJy4AhWRc2F
    url: jdbc:mysql://myserver.com:3306/luopc1218_develop
    username: root
logging:
  level:
    com:
      luopc1218:
        luopc1218server:
          repository: debug