minio:
  accessKey: minio
  endpoint: http://106.52.172.134:9000
  secretKey: minio@123
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  datasource:
    password: root
    url: jdbc:mysql://106.52.172.134:3306/luopc1218_develop
    username: root
logging:
  level:
    com:
      luopc1218:
        luopc1218server:
          repository: debug