minio:
  accessKey: luopc1218
  endpoint: http://106.52.172.134:9001
  secretKey: peichun92755
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  datasource:
    password: peichun92755
    url: jdbc:mysql://106.52.172.134:3306/luopc1218server_develop
    username: luopc1218
logging:
  level:
    com:
      luopc1218:
        luopc1218server:
          repository: debug